#!/bin/bash -l

# Input arguments
function parseArgs(){

  threads=1
  prefix="sars-cov-2"
  reference=""
  panel=""

	arg=$1
	while [[ "$arg" != "" ]]
	do
		case "$1" in
			"--infile")
			 shift
			 infile=$1
			 ;;
      "--outprefix")
       shift
       prefix=$1
       ;;
      "--reference")
       shift
       reference=$1
       ;;
      "--panel")
       shift
       panel=$1
       ;;       
      "--threads")
       shift
       threads=$1
       ;;
			*)
			 echo 'Unknown argument '$1
			 shift
		esac
		shift
		arg=$1
	done
}

parseArgs $@

# Build docker if not available
if [[ "$(docker images -q impusars 2> /dev/null)" == "" ]]; then
  echo >&2 "[ impuSARS ] Docker image NOT FOUND!"
  echo >&2 "[ impuSARS ] Please, install impuSARS image by running"
  echo >&2 "[ impuSARS ] the following command:"
  echo >&2 "[ impuSARS ] ./install_impuSARS"
  exit 1
fi

realp=`realpath $infile`
outpath=`dirname $realp`
file=`basename $infile`

opt_args=""
mnt_path=""
if [[ "$reference" != "" ]]; then
    realref=`realpath $reference`
    refpath=`dirname $realref`
    reffile=`basename $reference`
    mnt_path="${mnt_path} -v ${refpath}:/ref/ "
    opt_args="${opt_args} --reference /ref/${reffile} "
fi
if [[ "$panel" != "" ]]; then
    realpanel=`realpath $panel`
    panelpath=`dirname $realpanel`
    panelfile=`basename $panel`
    mnt_path="${mnt_path} -v ${panelpath}:/panel/ "
    opt_args="${opt_args} --panel /panel/${panelfile} "
fi

# Run docker
docker run -it --rm -v ${outpath}:/data impusars impuSARS ${mnt_path} \
           --infile /data/${file} --outprefix ${prefix} --threads ${threads} \
           ${opt_args}
