name: impusars
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - amply=0.1.4
  - appdirs=1.4.4
  - attrs=21.2.0
  - bcftools=1.11
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - biopython=1.74
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - cget=0.1.9
  - chardet=4.0.0
  - click=8.0.3
  - cmake=3.21.3
  - coincbc=2.10.5
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - constellations=0.0.21
  - cryptography=35.0.0
  - datrie=0.8.2
  - docutils=0.18
  - expat=2.4.1
  - filelock=3.3.2
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gitdb=4.0.9
  - gitpython=3.1.24
  - gofasta=0.0.5
  - gsl=2.6
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - htslib=1.11
  - icu=69.1
  - idna=2.10
  - importlib-metadata=4.8.1
  - ipython_genutils=0.2.0
  - joblib=1.1.0
  - jsonschema=4.1.2
  - jupyter_core=4.9.1
  - k8=0.2.5
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsanitizer=11.2.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.32.1
  - libuv=1.42.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mafft=7.490
  - make=4.3
  - minimap2=2.22
  - mpi=1.0
  - muscle=3.8.1551
  - mysql-connector-c=6.1.11
  - nbformat=5.1.3
  - ncurses=6.2
  - numpy=1.21.3
  - openmpi=4.1.1
  - openssl=1.1.1l
  - pandas=1.3.4
  - pango-designation=1.2.91
  - pangolearn=2021.10.13
  - pangolin=3.1.14
  - perl=5.32.1
  - pip=21.3.1
  - psutil=5.8.0
  - pulp=2.5.1
  - pycparser=2.20
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.17.3
  - pysam=0.17.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pyyaml=6.0
  - ratelimiter=1.2.0
  - readline=8.1
  - requests=2.25.1
  - rhash=1.4.1
  - samtools=1.11
  - scikit-learn=0.23.1
  - scipy=1.7.1
  - scorpio=0.3.14
  - setuptools=58.4.0
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - snakemake-minimal=6.8.0
  - snp-sites=2.5.1
  - sqlite=3.36.0
  - stopit=1.1.2
  - subprocess32=3.5.4
  - sysroot_linux-64=2.12
  - tabulate=0.8.9
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - toposort=1.7
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - ucsc-fatovcf=407
  - urllib3=1.26.7
  - usher=0.4.8
  - wheel=0.37.0
  - wrapt=1.13.3
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - cflib-pomo==1.3.0.0
